In [2]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory
#
# import os
# for dirname, _, filenames in os.walk('/kaggle/input'):
#     for filename in filenames:
#         print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

In [3]:
df = pd.read_csv('../titanic/train.csv')

In [4]:
from sklearn.model_selection import train_test_split

In [5]:
X_train, X_test = train_test_split(df,test_size=0.2, random_state=42)

In [6]:
df.shape

(891, 12)

In [7]:
X_train.shape, X_test.shape

((712, 12), (179, 12))

In [8]:
X_train.dtypes

PassengerId      int64
Survived         int64
Pclass           int64
Name               str
Sex                str
Age            float64
SibSp            int64
Parch            int64
Ticket             str
Fare           float64
Cabin              str
Embarked           str
dtype: object

In [9]:
df.isna().mean()

PassengerId    0.000000
Survived       0.000000
Pclass         0.000000
Name           0.000000
Sex            0.000000
Age            0.198653
SibSp          0.000000
Parch          0.000000
Ticket         0.000000
Fare           0.000000
Cabin          0.771044
Embarked       0.002245
dtype: float64

In [10]:
df['Ticket'].value_counts()

Ticket
347082             7
1601               7
CA. 2343           7
3101295            6
CA 2144            6
                  ..
SOTON/OQ 392076    1
211536             1
112053             1
111369             1
370376             1
Name: count, Length: 681, dtype: int64

In [11]:
X_train.drop(columns=['Name', 'Cabin', 'Ticket'], inplace=True)
X_test.drop(columns=['Name', 'Cabin', 'Ticket'], inplace=True)

In [12]:
X_train.head()

,PassengerId,Survived,Pclass,Sex,Age,SibSp,Parch,Fare,Embarked
331,332,0,1,male,45.5,0,0,28.5000,S
733,734,0,2,male,23.0,0,0,13.0000,S
382,383,0,3,male,32.0,0,0,7.9250,S
704,705,0,3,male,26.0,1,0,7.8542,S
813,814,0,3,female,6.0,4,2,31.2750,S

In [13]:
X_train.groupby('Sex').agg({'Survived' : 'mean'})

        Survived
Sex
female  0.738776
male    0.186296

In [14]:
X_train['gender_num'] = np.where(X_train['Sex'] == 'female', 1, 0)

In [15]:
X_test['gender_num'] = np.where(X_test['Sex'] == 'female', 1, 0)

In [16]:
X_train.head()

,PassengerId,Survived,Pclass,Sex,Age,SibSp,Parch,Fare,Embarked,gender_num
331,332,0,1,male,45.5,0,0,28.5000,S,0
733,734,0,2,male,23.0,0,0,13.0000,S,0
382,383,0,3,male,32.0,0,0,7.9250,S,0
704,705,0,3,male,26.0,1,0,7.8542,S,0
813,814,0,3,female,6.0,4,2,31.2750,S,1

In [17]:
X_test.head()

,PassengerId,Survived,Pclass,Sex,Age,SibSp,Parch,Fare,Embarked,gender_num
709,710,1,3,male,NaN,1,1,15.2458,C,0
439,440,0,2,male,31.0,0,0,10.5000,S,0
840,841,0,3,male,20.0,0,0,7.9250,S,0
720,721,1,2,female,6.0,0,1,33.0000,S,1
39,40,1,3,female,14.0,1,0,11.2417,C,1

In [18]:
X_train.groupby('Embarked').agg({'Survived' : 'mean'})

          Survived
Embarked
C         0.544000
Q         0.366667
S         0.335238

In [19]:
X_train['embarked_num'] = np.where(X_train['Embarked'] == 'C', 1, 0)
X_test['embarked_num'] = np.where(X_test['Embarked'] == 'C', 1, 0)

In [20]:
X_train.head()

,PassengerId,Survived,Pclass,Sex,Age,SibSp,Parch,Fare,Embarked,gender_num,embarked_num
331,332,0,1,male,45.5,0,0,28.5000,S,0,0
733,734,0,2,male,23.0,0,0,13.0000,S,0,0
382,383,0,3,male,32.0,0,0,7.9250,S,0,0
704,705,0,3,male,26.0,1,0,7.8542,S,0,0
813,814,0,3,female,6.0,4,2,31.2750,S,1,0

In [21]:
X_train.drop(columns=['Sex', 'Embarked'], inplace=True)
X_test.drop(columns=['Sex', 'Embarked'], inplace=True)

In [22]:
X_train.head()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare,gender_num,embarked_num
331,332,0,1,45.5,0,0,28.5000,0,0
733,734,0,2,23.0,0,0,13.0000,0,0
382,383,0,3,32.0,0,0,7.9250,0,0
704,705,0,3,26.0,1,0,7.8542,0,0
813,814,0,3,6.0,4,2,31.2750,1,0

In [23]:
X_test.head()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare,gender_num,embarked_num
709,710,1,3,NaN,1,1,15.2458,0,1
439,440,0,2,31.0,0,0,10.5000,0,0
840,841,0,3,20.0,0,0,7.9250,0,0
720,721,1,2,6.0,0,1,33.0000,1,0
39,40,1,3,14.0,1,0,11.2417,1,1

In [24]:

X_train.isna().mean()

PassengerId     0.000000
Survived        0.000000
Pclass          0.000000
Age             0.196629
SibSp           0.000000
Parch           0.000000
Fare            0.000000
gender_num      0.000000
embarked_num    0.000000
dtype: float64

In [25]:
X_train['Age'].mode()

0    24.0
Name: Age, dtype: float64

In [26]:
X_train.fillna(24, inplace=True)

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare,gender_num,embarked_num
331,332,0,1,45.5,0,0,28.5000,0,0
733,734,0,2,23.0,0,0,13.0000,0,0
382,383,0,3,32.0,0,0,7.9250,0,0
704,705,0,3,26.0,1,0,7.8542,0,0
813,814,0,3,6.0,4,2,31.2750,1,0
...,...,...,...,...,...,...,...,...,...
106,107,1,3,21.0,0,0,7.6500,1,0
270,271,0,1,24.0,0,0,31.0000,0,0
860,861,0,3,41.0,2,0,14.1083,0,0
435,436,1,1,14.0,1,2,120.0000,1,0
102,103,0,1,21.0,0,1,77.2875,0,0

In [27]:
X_test.fillna(24, inplace=True)

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare,gender_num,embarked_num
709,710,1,3,24.0,1,1,15.2458,0,1
439,440,0,2,31.0,0,0,10.5000,0,0
840,841,0,3,20.0,0,0,7.9250,0,0
720,721,1,2,6.0,0,1,33.0000,1,0
39,40,1,3,14.0,1,0,11.2417,1,1
...,...,...,...,...,...,...,...,...,...
433,434,0,3,17.0,0,0,7.1250,0,0
773,774,0,3,24.0,0,0,7.2250,0,1
25,26,1,3,38.0,1,5,31.3875,1,0
84,85,1,2,17.0,0,0,10.5000,1,0
10,11,1,3,4.0,1,1,16.7000,1,0

In [28]:
X_train.isna().mean()

PassengerId     0.0
Survived        0.0
Pclass          0.0
Age             0.0
SibSp           0.0
Parch           0.0
Fare            0.0
gender_num      0.0
embarked_num    0.0
dtype: float64

In [29]:
X_test.isna().mean()

PassengerId     0.0
Survived        0.0
Pclass          0.0
Age             0.0
SibSp           0.0
Parch           0.0
Fare            0.0
gender_num      0.0
embarked_num    0.0
dtype: float64

In [30]:
X_train.head()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare,gender_num,embarked_num
331,332,0,1,45.5,0,0,28.5000,0,0
733,734,0,2,23.0,0,0,13.0000,0,0
382,383,0,3,32.0,0,0,7.9250,0,0
704,705,0,3,26.0,1,0,7.8542,0,0
813,814,0,3,6.0,4,2,31.2750,1,0

In [31]:
X_train = X_train.reset_index(drop=True)
X_test = X_test.reset_index(drop=True)

In [32]:
X_train

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare,gender_num,embarked_num
0,332,0,1,45.5,0,0,28.5000,0,0
1,734,0,2,23.0,0,0,13.0000,0,0
2,383,0,3,32.0,0,0,7.9250,0,0
3,705,0,3,26.0,1,0,7.8542,0,0
4,814,0,3,6.0,4,2,31.2750,1,0
...,...,...,...,...,...,...,...,...,...
707,107,1,3,21.0,0,0,7.6500,1,0
708,271,0,1,24.0,0,0,31.0000,0,0
709,861,0,3,41.0,2,0,14.1083,0,0
710,436,1,1,14.0,1,2,120.0000,1,0
711,103,0,1,21.0,0,1,77.2875,0,0

In [33]:
X_test

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare,gender_num,embarked_num
0,710,1,3,24.0,1,1,15.2458,0,1
1,440,0,2,31.0,0,0,10.5000,0,0
2,841,0,3,20.0,0,0,7.9250,0,0
3,721,1,2,6.0,0,1,33.0000,1,0
4,40,1,3,14.0,1,0,11.2417,1,1
...,...,...,...,...,...,...,...,...,...
174,434,0,3,17.0,0,0,7.1250,0,0
175,774,0,3,24.0,0,0,7.2250,0,1
176,26,1,3,38.0,1,5,31.3875,1,0
177,85,1,2,17.0,0,0,10.5000,1,0
178,11,1,3,4.0,1,1,16.7000,1,0

# Start Training

In [34]:
y_train = X_train.pop('Survived')
y_test = X_test.pop('Survived')

In [35]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import GridSearchCV, KFold
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler, MinMaxScaler

pipeline = Pipeline([
    ('scaler', StandardScaler()),  # This will be replaced during grid search
    ('classifier', LogisticRegression(max_iter=1000))
])

scalers = [
    StandardScaler(),
    MinMaxScaler(),
    None  # Option to use no scaler
]

kfold = KFold(n_splits=5, shuffle=True, random_state=42)

param_grid = {
    'scaler': scalers,
    'classifier__C': [0.1, 1, 10],  # Example hyperparameter for Logistic Regression
}

In [36]:
grid_search = GridSearchCV(
    pipeline,
    param_grid=param_grid,
    cv=kfold,
    scoring='f1',  # or any other metric
    verbose=2,
    return_train_score=True
)

In [37]:
grid_search.fit(X_train, y_train)

Fitting 5 folds for each of 9 candidates, totalling 45 fits
[CV] END .........classifier__C=0.1, scaler=StandardScaler(); total time=   0.0s
[CV] END .........classifier__C=0.1, scaler=StandardScaler(); total time=   0.0s
[CV] END .........classifier__C=0.1, scaler=StandardScaler(); total time=   0.0s
[CV] END .........classifier__C=0.1, scaler=StandardScaler(); total time=   0.0s
[CV] END .........classifier__C=0.1, scaler=StandardScaler(); total time=   0.0s
[CV] END ...........classifier__C=0.1, scaler=MinMaxScaler(); total time=   0.0s
[CV] END ...........classifier__C=0.1, scaler=MinMaxScaler(); total time=   0.0s
[CV] END ...........classifier__C=0.1, scaler=MinMaxScaler(); total time=   0.0s
[CV] END ...........classifier__C=0.1, scaler=MinMaxScaler(); total time=   0.0s
[CV] END ...........classifier__C=0.1, scaler=MinMaxScaler(); total time=   0.0s
[CV] END .....................classifier__C=0.1, scaler=None; total time=   0.3s
[CV] END .....................classifier__C=0.1, scaler=None; total time=   0.5s
[CV] END .....................classifier__C=0.1, scaler=None; total time=   0.4s
[CV] END .....................classifier__C=0.1, scaler=None; total time=   0.3s
[CV] END .....................classifier__C=0.1, scaler=None; total time=   0.6s
[CV] END ...........classifier__C=1, scaler=StandardScaler(); total time=   0.0s
[CV] END ...........classifier__C=1, scaler=StandardScaler(); total time=   0.0s
[CV] END ...........classifier__C=1, scaler=StandardScaler(); total time=   0.0s
[CV] END ...........classifier__C=1, scaler=StandardScaler(); total time=   0.0s
[CV] END ...........classifier__C=1, scaler=StandardScaler(); total time=   0.0s
[CV] END .............classifier__C=1, scaler=MinMaxScaler(); total time=   0.0s
[CV] END .............classifier__C=1, scaler=MinMaxScaler(); total time=   0.0s
[CV] END .............classifier__C=1, scaler=MinMaxScaler(); total time=   0.0s
[CV] END .............classifier__C=1, scaler=MinMaxScaler(); total time=   0.0s
[CV] END .............classifier__C=1, scaler=MinMaxScaler(); total time=   0.0s
[CV] END .......................classifier__C=1, scaler=None; total time=   0.2s
[CV] END .......................classifier__C=1, scaler=None; total time=   0.6s
[CV] END .......................classifier__C=1, scaler=None; total time=   0.5s
[CV] END .......................classifier__C=1, scaler=None; total time=   0.4s
[CV] END .......................classifier__C=1, scaler=None; total time=   0.4s
[CV] END ..........classifier__C=10, scaler=StandardScaler(); total time=   0.0s
[CV] END ..........classifier__C=10, scaler=StandardScaler(); total time=   0.0s
[CV] END ..........classifier__C=10, scaler=StandardScaler(); total time=   0.0s
[CV] END ..........classifier__C=10, scaler=StandardScaler(); total time=   0.0s
[CV] END ..........classifier__C=10, scaler=StandardScaler(); total time=   0.0s
[CV] END ............classifier__C=10, scaler=MinMaxScaler(); total time=   0.0s
[CV] END ............classifier__C=10, scaler=MinMaxScaler(); total time=   0.0s
[CV] END ............classifier__C=10, scaler=MinMaxScaler(); total time=   0.0s
[CV] END ............classifier__C=10, scaler=MinMaxScaler(); total time=   0.0s
[CV] END ............classifier__C=10, scaler=MinMaxScaler(); total time=   0.0s
[CV] END ......................classifier__C=10, scaler=None; total time=   0.4s
[CV] END ......................classifier__C=10, scaler=None; total time=   0.3s
[CV] END ......................classifier__C=10, scaler=None; total time=   0.5s
[CV] END ......................classifier__C=10, scaler=None; total time=   0.4s
[CV] END ......................classifier__C=10, scaler=None; total time=   0.7s

GridSearchCV(cv=KFold(n_splits=5, random_state=42, shuffle=True),
             estimator=Pipeline(steps=[('scaler', StandardScaler()),
                                       ('classifier',
                                        LogisticRegression(max_iter=1000))]),
             param_grid={'classifier__C': [0.1, 1, 10],
                         'scaler': [StandardScaler(), MinMaxScaler(), None]},
             return_train_score=True, scoring='f1', verbose=2)

In [38]:
print(f"Best parameters: {grid_search.best_params_}")
print(f"Best cross-validation score: {grid_search.best_score_:.4f}")

Best parameters: {'classifier__C': 0.1, 'scaler': StandardScaler()}
Best cross-validation score: 0.7161

In [39]:
results = pd.DataFrame(grid_search.cv_results_)
results = results.sort_values('rank_test_score')

In [40]:
results.columns

Index(['mean_fit_time', 'std_fit_time', 'mean_score_time', 'std_score_time',
       'param_classifier__C', 'param_scaler', 'params', 'split0_test_score',
       'split1_test_score', 'split2_test_score', 'split3_test_score',
       'split4_test_score', 'mean_test_score', 'std_test_score',
       'rank_test_score', 'split0_train_score', 'split1_train_score',
       'split2_train_score', 'split3_train_score', 'split4_train_score',
       'mean_train_score', 'std_train_score'],
      dtype='str')

In [41]:
print(results[['param_scaler', 'param_classifier__C', 'mean_train_score', 'mean_test_score']])

       param_scaler  param_classifier__C  mean_train_score  mean_test_score
0  StandardScaler()                  0.1          0.727609         0.716144
4    MinMaxScaler()                  1.0          0.720759         0.713530
7    MinMaxScaler()                 10.0          0.724909         0.711158
5              None                  1.0          0.726455         0.710766
3  StandardScaler()                  1.0          0.725276         0.708720
6  StandardScaler()                 10.0          0.725622         0.707431
8              None                 10.0          0.725604         0.707431
1    MinMaxScaler()                  0.1          0.712874         0.706172
2              None                  0.1          0.716930         0.699464

In [42]:
best_pipeline = grid_search.best_estimator_

In [43]:
!pip install dagshub

Requirement already satisfied: dagshub in c:\users\lukas\appdata\local\programs\python\python314\lib\site-packages (0.6.9)
Requirement already satisfied: PyYAML>=5 in c:\users\lukas\appdata\local\programs\python\python314\lib\site-packages (from dagshub) (6.0.3)
Requirement already satisfied: appdirs>=1.4.4 in c:\users\lukas\appdata\local\programs\python\python314\lib\site-packages (from dagshub) (1.4.4)
Requirement already satisfied: click>=8.0.4 in c:\users\lukas\appdata\local\programs\python\python314\lib\site-packages (from dagshub) (8.3.1)
Requirement already satisfied: httpx>=0.23.0 in c:\users\lukas\appdata\local\programs\python\python314\lib\site-packages (from dagshub) (0.28.1)
Requirement already satisfied: GitPython>=3.1.29 in c:\users\lukas\appdata\local\programs\python\python314\lib\site-packages (from dagshub) (3.1.46)
Requirement already satisfied: rich>=13.1.0 in c:\users\lukas\appdata\local\programs\python\python314\lib\site-packages (from dagshub) (14.3.3)
Requirement already satisfied: dacite~=1.6.0 in c:\users\lukas\appdata\local\programs\python\python314\lib\site-packages (from dagshub) (1.6.0)
Requirement already satisfied: tenacity>=8.2.2 in c:\users\lukas\appdata\local\programs\python\python314\lib\site-packages (from dagshub) (9.1.4)
Requirement already satisfied: gql[requests] in c:\users\lukas\appdata\local\programs\python\python314\lib\site-packages (from dagshub) (4.0.0)
Requirement already satisfied: dataclasses-json in c:\users\lukas\appdata\local\programs\python\python314\lib\site-packages (from dagshub) (0.6.7)
Requirement already satisfied: pandas in c:\users\lukas\appdata\local\programs\python\python314\lib\site-packages (from dagshub) (3.0.1)
Requirement already satisfied: treelib>=1.6.4 in c:\users\lukas\appdata\local\programs\python\python314\lib\site-packages (from dagshub) (1.8.0)
Requirement already satisfied: pathvalidate>=3.0.0 in c:\users\lukas\appdata\local\programs\python\python314\lib\site-packages (from dagshub) (3.3.1)
Requirement already satisfied: python-dateutil in c:\users\lukas\appdata\local\programs\python\python314\lib\site-packages (from dagshub) (2.9.0.post0)
Requirement already satisfied: boto3 in c:\users\lukas\appdata\local\programs\python\python314\lib\site-packages (from dagshub) (1.42.78)
Requirement already satisfied: semver in c:\users\lukas\appdata\local\programs\python\python314\lib\site-packages (from dagshub) (3.0.4)
Requirement already satisfied: dagshub-annotation-converter>=0.1.12 in c:\users\lukas\appdata\local\programs\python\python314\lib\site-packages (from dagshub) (0.1.16)
Requirement already satisfied: colorama in c:\users\lukas\appdata\local\programs\python\python314\lib\site-packages (from click>=8.0.4->dagshub) (0.4.6)
Requirement already satisfied: lxml in c:\users\lukas\appdata\local\programs\python\python314\lib\site-packages (from dagshub-annotation-converter>=0.1.12->dagshub) (6.0.2)
Requirement already satisfied: pillow in c:\users\lukas\appdata\local\programs\python\python314\lib\site-packages (from dagshub-annotation-converter>=0.1.12->dagshub) (12.1.1)
Requirement already satisfied: pydantic>=2.0.0 in c:\users\lukas\appdata\local\programs\python\python314\lib\site-packages (from dagshub-annotation-converter>=0.1.12->dagshub) (2.12.5)
Requirement already satisfied: typing-extensions in c:\users\lukas\appdata\local\programs\python\python314\lib\site-packages (from dagshub-annotation-converter>=0.1.12->dagshub) (4.15.0)
Requirement already satisfied: gitdb<5,>=4.0.1 in c:\users\lukas\appdata\local\programs\python\python314\lib\site-packages (from GitPython>=3.1.29->dagshub) (4.0.12)
Requirement already satisfied: smmap<6,>=3.0.1 in c:\users\lukas\appdata\local\programs\python\python314\lib\site-packages (from gitdb<5,>=4.0.1->GitPython>=3.1.29->dagshub) (5.0.3)
Requirement already satisfied: anyio in c:\users\lukas\appdata\local\programs\python\python314\lib\site-packages (from httpx>=0.23.0->dagshub) (4.13.0)
Requirement already satisfied: certifi in c:\users\lukas\appdata\local\programs\python\python314\lib\site-packages (from httpx>=0.23.0->dagshub) (2026.2.25)
Requirement already satisfied: httpcore==1.* in c:\users\lukas\appdata\local\programs\python\python314\lib\site-packages (from httpx>=0.23.0->dagshub) (1.0.9)
Requirement already satisfied: idna in c:\users\lukas\appdata\local\programs\python\python314\lib\site-packages (from httpx>=0.23.0->dagshub) (3.11)
Requirement already satisfied: h11>=0.16 in c:\users\lukas\appdata\local\programs\python\python314\lib\site-packages (from httpcore==1.*->httpx>=0.23.0->dagshub) (0.16.0)
Requirement already satisfied: annotated-types>=0.6.0 in c:\users\lukas\appdata\local\programs\python\python314\lib\site-packages (from pydantic>=2.0.0->dagshub-annotation-converter>=0.1.12->dagshub) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.5 in c:\users\lukas\appdata\local\programs\python\python314\lib\site-packages (from pydantic>=2.0.0->dagshub-annotation-converter>=0.1.12->dagshub) (2.41.5)
Requirement already satisfied: typing-inspection>=0.4.2 in c:\users\lukas\appdata\local\programs\python\python314\lib\site-packages (from pydantic>=2.0.0->dagshub-annotation-converter>=0.1.12->dagshub) (0.4.2)
Requirement already satisfied: markdown-it-py>=2.2.0 in c:\users\lukas\appdata\local\programs\python\python314\lib\site-packages (from rich>=13.1.0->dagshub) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in c:\users\lukas\appdata\local\programs\python\python314\lib\site-packages (from rich>=13.1.0->dagshub) (2.20.0)
Requirement already satisfied: mdurl~=0.1 in c:\users\lukas\appdata\local\programs\python\python314\lib\site-packages (from markdown-it-py>=2.2.0->rich>=13.1.0->dagshub) (0.1.2)
Requirement already satisfied: six>=1.13.0 in c:\users\lukas\appdata\local\programs\python\python314\lib\site-packages (from treelib>=1.6.4->dagshub) (1.17.0)
Requirement already satisfied: botocore<1.43.0,>=1.42.78 in c:\users\lukas\appdata\local\programs\python\python314\lib\site-packages (from boto3->dagshub) (1.42.78)
Requirement already satisfied: jmespath<2.0.0,>=0.7.1 in c:\users\lukas\appdata\local\programs\python\python314\lib\site-packages (from boto3->dagshub) (1.1.0)
Requirement already satisfied: s3transfer<0.17.0,>=0.16.0 in c:\users\lukas\appdata\local\programs\python\python314\lib\site-packages (from boto3->dagshub) (0.16.0)
Requirement already satisfied: urllib3!=2.2.0,<3,>=1.25.4 in c:\users\lukas\appdata\local\programs\python\python314\lib\site-packages (from botocore<1.43.0,>=1.42.78->boto3->dagshub) (2.6.3)
Requirement already satisfied: marshmallow<4.0.0,>=3.18.0 in c:\users\lukas\appdata\local\programs\python\python314\lib\site-packages (from dataclasses-json->dagshub) (3.26.2)
Requirement already satisfied: typing-inspect<1,>=0.4.0 in c:\users\lukas\appdata\local\programs\python\python314\lib\site-packages (from dataclasses-json->dagshub) (0.9.0)
Requirement already satisfied: packaging>=17.0 in c:\users\lukas\appdata\local\programs\python\python314\lib\site-packages (from marshmallow<4.0.0,>=3.18.0->dataclasses-json->dagshub) (26.0)
Requirement already satisfied: mypy-extensions>=0.3.0 in c:\users\lukas\appdata\local\programs\python\python314\lib\site-packages (from typing-inspect<1,>=0.4.0->dataclasses-json->dagshub) (1.1.0)
Requirement already satisfied: graphql-core<3.3,>=3.2 in c:\users\lukas\appdata\local\programs\python\python314\lib\site-packages (from gql[requests]->dagshub) (3.2.8)
Requirement already satisfied: yarl<2.0,>=1.6 in c:\users\lukas\appdata\local\programs\python\python314\lib\site-packages (from gql[requests]->dagshub) (1.23.0)
Requirement already satisfied: backoff<3.0,>=1.11.1 in c:\users\lukas\appdata\local\programs\python\python314\lib\site-packages (from gql[requests]->dagshub) (2.2.1)
Requirement already satisfied: requests<3,>=2.26 in c:\users\lukas\appdata\local\programs\python\python314\lib\site-packages (from gql[requests]->dagshub) (2.33.0)
Requirement already satisfied: requests_toolbelt<2,>=1.0.0 in c:\users\lukas\appdata\local\programs\python\python314\lib\site-packages (from gql[requests]->dagshub) (1.0.0)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\lukas\appdata\local\programs\python\python314\lib\site-packages (from requests<3,>=2.26->gql[requests]->dagshub) (3.4.6)
Requirement already satisfied: multidict>=4.0 in c:\users\lukas\appdata\local\programs\python\python314\lib\site-packages (from yarl<2.0,>=1.6->gql[requests]->dagshub) (6.7.1)
Requirement already satisfied: propcache>=0.2.1 in c:\users\lukas\appdata\local\programs\python\python314\lib\site-packages (from yarl<2.0,>=1.6->gql[requests]->dagshub) (0.4.1)
Requirement already satisfied: numpy>=2.3.3 in c:\users\lukas\appdata\local\programs\python\python314\lib\site-packages (from pandas->dagshub) (2.4.4)
Requirement already satisfied: tzdata in c:\users\lukas\appdata\local\programs\python\python314\lib\site-packages (from pandas->dagshub) (2025.3)

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [46]:
import dagshub

# შემდეგ cell - ში თქვენი რეპოზიტორიის ინფორმაცია შეიყვანეთ

In [49]:
# import dagshub
dagshub.init(repo_owner='lukaLomadze', repo_name='ML', mlflow=True)

                                       ❗❗❗ AUTHORIZATION REQUIRED ❗❗❗

C:\Users\lukas\AppData\Local\Programs\Python\Python314\Lib\site-packages\rich\live.py:260: UserWarning: install
"ipywidgets" for Jupyter support
  warnings.warn('install "ipywidgets" for Jupyter support')

Open the following link in your browser to authorize the client:
https://dagshub.com/login/oauth/authorize?state=68aed506-ba6c-4d9d-9290-32f93be52dd3&client_id=32b60ba385aa7cecf24046d8195a71c07dd345d9657977863b52e7748e0f0f28&middleman_request_id=279022ddd09105f51a659f31ff1849f4e404161269bf514f78f8de1a42140ea5

Accessing as lukaLomadze

Initialized MLflow to track repo "lukaLomadze/ML"

Repository lukaLomadze/ML initialized!

In [45]:
!pip install mlflow

Collecting mlflow
  Downloading mlflow-2.21.0-py3-none-any.whl.metadata (30 kB)
Collecting mlflow-skinny==2.21.0 (from mlflow)
  Downloading mlflow_skinny-2.21.0-py3-none-any.whl.metadata (31 kB)
Requirement already satisfied: Flask<4 in /usr/local/lib/python3.10/dist-packages (from mlflow) (3.1.0)
Requirement already satisfied: Jinja2<4,>=2.11 in /usr/local/lib/python3.10/dist-packages (from mlflow) (3.1.4)
Requirement already satisfied: alembic!=1.10.0,<2 in /usr/local/lib/python3.10/dist-packages (from mlflow) (1.14.1)
Requirement already satisfied: docker<8,>=4.0.0 in /usr/local/lib/python3.10/dist-packages (from mlflow) (7.1.0)
Collecting graphene<4 (from mlflow)
  Downloading graphene-3.4.3-py2.py3-none-any.whl.metadata (6.9 kB)
Collecting gunicorn<24 (from mlflow)
  Downloading gunicorn-23.0.0-py3-none-any.whl.metadata (4.4 kB)
Requirement already satisfied: markdown<4,>=3.3 in /usr/local/lib/python3.10/dist-packages (from mlflow) (3.7)
Requirement already satisfied: matplotlib<4 in /usr/local/lib/python3.10/dist-packages (from mlflow) (3.7.5)
Requirement already satisfied: numpy<3 in /usr/local/lib/python3.10/dist-packages (from mlflow) (1.26.4)
Requirement already satisfied: pandas<3 in /usr/local/lib/python3.10/dist-packages (from mlflow) (2.2.3)
Requirement already satisfied: pyarrow<20,>=4.0.0 in /usr/local/lib/python3.10/dist-packages (from mlflow) (19.0.1)
Requirement already satisfied: scikit-learn<2 in /usr/local/lib/python3.10/dist-packages (from mlflow) (1.2.2)
Requirement already satisfied: scipy<2 in /usr/local/lib/python3.10/dist-packages (from mlflow) (1.13.1)
Requirement already satisfied: sqlalchemy<3,>=1.4.0 in /usr/local/lib/python3.10/dist-packages (from mlflow) (2.0.36)
Requirement already satisfied: cachetools<6,>=5.0.0 in /usr/local/lib/python3.10/dist-packages (from mlflow-skinny==2.21.0->mlflow) (5.5.0)
Requirement already satisfied: click<9,>=7.0 in /usr/local/lib/python3.10/dist-packages (from mlflow-skinny==2.21.0->mlflow) (8.1.7)
Requirement already satisfied: cloudpickle<4 in /usr/local/lib/python3.10/dist-packages (from mlflow-skinny==2.21.0->mlflow) (3.1.0)
Collecting databricks-sdk<1,>=0.20.0 (from mlflow-skinny==2.21.0->mlflow)
  Downloading databricks_sdk-0.46.0-py3-none-any.whl.metadata (38 kB)
Collecting fastapi<1 (from mlflow-skinny==2.21.0->mlflow)
  Downloading fastapi-0.115.11-py3-none-any.whl.metadata (27 kB)
Requirement already satisfied: gitpython<4,>=3.1.9 in /usr/local/lib/python3.10/dist-packages (from mlflow-skinny==2.21.0->mlflow) (3.1.43)
Requirement already satisfied: importlib_metadata!=4.7.0,<9,>=3.7.0 in /usr/local/lib/python3.10/dist-packages (from mlflow-skinny==2.21.0->mlflow) (8.5.0)
Requirement already satisfied: opentelemetry-api<3,>=1.9.0 in /usr/local/lib/python3.10/dist-packages (from mlflow-skinny==2.21.0->mlflow) (1.29.0)
Requirement already satisfied: opentelemetry-sdk<3,>=1.9.0 in /usr/local/lib/python3.10/dist-packages (from mlflow-skinny==2.21.0->mlflow) (1.29.0)
Requirement already satisfied: packaging<25 in /usr/local/lib/python3.10/dist-packages (from mlflow-skinny==2.21.0->mlflow) (24.2)
Requirement already satisfied: protobuf<6,>=3.12.0 in /usr/local/lib/python3.10/dist-packages (from mlflow-skinny==2.21.0->mlflow) (3.20.3)
Requirement already satisfied: pydantic<3,>=1.10.8 in /usr/local/lib/python3.10/dist-packages (from mlflow-skinny==2.21.0->mlflow) (2.11.0a2)
Requirement already satisfied: pyyaml<7,>=5.1 in /usr/local/lib/python3.10/dist-packages (from mlflow-skinny==2.21.0->mlflow) (6.0.2)
Requirement already satisfied: requests<3,>=2.17.3 in /usr/local/lib/python3.10/dist-packages (from mlflow-skinny==2.21.0->mlflow) (2.32.3)
Requirement already satisfied: sqlparse<1,>=0.4.0 in /usr/local/lib/python3.10/dist-packages (from mlflow-skinny==2.21.0->mlflow) (0.5.3)
Requirement already satisfied: typing-extensions<5,>=4.0.0 in /usr/local/lib/python3.10/dist-packages (from mlflow-skinny==2.21.0->mlflow) (4.12.2)
Collecting uvicorn<1 (from mlflow-skinny==2.21.0->mlflow)
  Downloading uvicorn-0.34.0-py3-none-any.whl.metadata (6.5 kB)
Requirement already satisfied: Mako in /usr/local/lib/python3.10/dist-packages (from alembic!=1.10.0,<2->mlflow) (1.3.9)
Requirement already satisfied: urllib3>=1.26.0 in /usr/local/lib/python3.10/dist-packages (from docker<8,>=4.0.0->mlflow) (2.3.0)
Requirement already satisfied: Werkzeug>=3.1 in /usr/local/lib/python3.10/dist-packages (from Flask<4->mlflow) (3.1.3)
Requirement already satisfied: itsdangerous>=2.2 in /usr/local/lib/python3.10/dist-packages (from Flask<4->mlflow) (2.2.0)
Requirement already satisfied: blinker>=1.9 in /usr/local/lib/python3.10/dist-packages (from Flask<4->mlflow) (1.9.0)
Requirement already satisfied: graphql-core<3.3,>=3.1 in /usr/local/lib/python3.10/dist-packages (from graphene<4->mlflow) (3.2.4)
Collecting graphql-relay<3.3,>=3.1 (from graphene<4->mlflow)
  Downloading graphql_relay-3.2.0-py3-none-any.whl.metadata (12 kB)
Requirement already satisfied: python-dateutil<3,>=2.7.0 in /usr/local/lib/python3.10/dist-packages (from graphene<4->mlflow) (2.9.0.post0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.10/dist-packages (from Jinja2<4,>=2.11->mlflow) (3.0.2)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib<4->mlflow) (1.3.1)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.10/dist-packages (from matplotlib<4->mlflow) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.10/dist-packages (from matplotlib<4->mlflow) (4.55.3)
Requirement already satisfied: kiwisolver>=1.0.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib<4->mlflow) (1.4.7)
Requirement already satisfied: pillow>=6.2.0 in /usr/local/lib/python3.10/dist-packages (from matplotlib<4->mlflow) (11.0.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib<4->mlflow) (3.2.0)
Requirement already satisfied: mkl_fft in /usr/local/lib/python3.10/dist-packages (from numpy<3->mlflow) (1.3.8)
Requirement already satisfied: mkl_random in /usr/local/lib/python3.10/dist-packages (from numpy<3->mlflow) (1.2.4)
Requirement already satisfied: mkl_umath in /usr/local/lib/python3.10/dist-packages (from numpy<3->mlflow) (0.1.1)
Requirement already satisfied: mkl in /usr/local/lib/python3.10/dist-packages (from numpy<3->mlflow) (2025.0.1)
Requirement already satisfied: tbb4py in /usr/local/lib/python3.10/dist-packages (from numpy<3->mlflow) (2022.0.0)
Requirement already satisfied: mkl-service in /usr/local/lib/python3.10/dist-packages (from numpy<3->mlflow) (2.4.1)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas<3->mlflow) (2025.1)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.10/dist-packages (from pandas<3->mlflow) (2025.1)
Requirement already satisfied: joblib>=1.1.1 in /usr/local/lib/python3.10/dist-packages (from scikit-learn<2->mlflow) (1.4.2)
Requirement already satisfied: threadpoolctl>=2.0.0 in /usr/local/lib/python3.10/dist-packages (from scikit-learn<2->mlflow) (3.5.0)
Requirement already satisfied: greenlet!=0.4.17 in /usr/local/lib/python3.10/dist-packages (from sqlalchemy<3,>=1.4.0->mlflow) (3.1.1)
Requirement already satisfied: google-auth~=2.0 in /usr/local/lib/python3.10/dist-packages (from databricks-sdk<1,>=0.20.0->mlflow-skinny==2.21.0->mlflow) (2.27.0)
Collecting starlette<0.47.0,>=0.40.0 (from fastapi<1->mlflow-skinny==2.21.0->mlflow)
  Downloading starlette-0.46.1-py3-none-any.whl.metadata (6.2 kB)
Requirement already satisfied: gitdb<5,>=4.0.1 in /usr/local/lib/python3.10/dist-packages (from gitpython<4,>=3.1.9->mlflow-skinny==2.21.0->mlflow) (4.0.11)
Requirement already satisfied: zipp>=3.20 in /usr/local/lib/python3.10/dist-packages (from importlib_metadata!=4.7.0,<9,>=3.7.0->mlflow-skinny==2.21.0->mlflow) (3.21.0)
Requirement already satisfied: deprecated>=1.2.6 in /usr/local/lib/python3.10/dist-packages (from opentelemetry-api<3,>=1.9.0->mlflow-skinny==2.21.0->mlflow) (1.2.15)
Requirement already satisfied: opentelemetry-semantic-conventions==0.50b0 in /usr/local/lib/python3.10/dist-packages (from opentelemetry-sdk<3,>=1.9.0->mlflow-skinny==2.21.0->mlflow) (0.50b0)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.10/dist-packages (from pydantic<3,>=1.10.8->mlflow-skinny==2.21.0->mlflow) (0.7.0)
Requirement already satisfied: pydantic-core==2.29.0 in /usr/local/lib/python3.10/dist-packages (from pydantic<3,>=1.10.8->mlflow-skinny==2.21.0->mlflow) (2.29.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil<3,>=2.7.0->graphene<4->mlflow) (1.17.0)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests<3,>=2.17.3->mlflow-skinny==2.21.0->mlflow) (3.4.1)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests<3,>=2.17.3->mlflow-skinny==2.21.0->mlflow) (3.10)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests<3,>=2.17.3->mlflow-skinny==2.21.0->mlflow) (2025.1.31)
Requirement already satisfied: h11>=0.8 in /usr/local/lib/python3.10/dist-packages (from uvicorn<1->mlflow-skinny==2.21.0->mlflow) (0.14.0)
Requirement already satisfied: intel-openmp>=2024 in /usr/local/lib/python3.10/dist-packages (from mkl->numpy<3->mlflow) (2024.2.0)
Requirement already satisfied: tbb==2022.* in /usr/local/lib/python3.10/dist-packages (from mkl->numpy<3->mlflow) (2022.0.0)
Requirement already satisfied: tcmlib==1.* in /usr/local/lib/python3.10/dist-packages (from tbb==2022.*->mkl->numpy<3->mlflow) (1.2.0)
Requirement already satisfied: intel-cmplr-lib-rt in /usr/local/lib/python3.10/dist-packages (from mkl_umath->numpy<3->mlflow) (2024.2.0)
Requirement already satisfied: wrapt<2,>=1.10 in /usr/local/lib/python3.10/dist-packages (from deprecated>=1.2.6->opentelemetry-api<3,>=1.9.0->mlflow-skinny==2.21.0->mlflow) (1.17.0)
Requirement already satisfied: smmap<6,>=3.0.1 in /usr/local/lib/python3.10/dist-packages (from gitdb<5,>=4.0.1->gitpython<4,>=3.1.9->mlflow-skinny==2.21.0->mlflow) (5.0.1)
Requirement already satisfied: pyasn1-modules>=0.2.1 in /usr/local/lib/python3.10/dist-packages (from google-auth~=2.0->databricks-sdk<1,>=0.20.0->mlflow-skinny==2.21.0->mlflow) (0.4.1)
Requirement already satisfied: rsa<5,>=3.1.4 in /usr/local/lib/python3.10/dist-packages (from google-auth~=2.0->databricks-sdk<1,>=0.20.0->mlflow-skinny==2.21.0->mlflow) (4.9)
Requirement already satisfied: intel-cmplr-lib-ur==2024.2.0 in /usr/local/lib/python3.10/dist-packages (from intel-openmp>=2024->mkl->numpy<3->mlflow) (2024.2.0)
Requirement already satisfied: anyio<5,>=3.6.2 in /usr/local/lib/python3.10/dist-packages (from starlette<0.47.0,>=0.40.0->fastapi<1->mlflow-skinny==2.21.0->mlflow) (3.7.1)
Requirement already satisfied: sniffio>=1.1 in /usr/local/lib/python3.10/dist-packages (from anyio<5,>=3.6.2->starlette<0.47.0,>=0.40.0->fastapi<1->mlflow-skinny==2.21.0->mlflow) (1.3.1)
Requirement already satisfied: exceptiongroup in /usr/local/lib/python3.10/dist-packages (from anyio<5,>=3.6.2->starlette<0.47.0,>=0.40.0->fastapi<1->mlflow-skinny==2.21.0->mlflow) (1.2.2)
Requirement already satisfied: pyasn1<0.7.0,>=0.4.6 in /usr/local/lib/python3.10/dist-packages (from pyasn1-modules>=0.2.1->google-auth~=2.0->databricks-sdk<1,>=0.20.0->mlflow-skinny==2.21.0->mlflow) (0.6.1)
Downloading mlflow-2.21.0-py3-none-any.whl (28.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 28.2/28.2 MB 49.4 MB/s eta 0:00:00:00:0100:01
Downloading mlflow_skinny-2.21.0-py3-none-any.whl (6.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.1/6.1 MB 74.4 MB/s eta 0:00:00:00:0100:01
Downloading graphene-3.4.3-py2.py3-none-any.whl (114 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 114.9/114.9 kB 4.5 MB/s eta 0:00:00
Downloading gunicorn-23.0.0-py3-none-any.whl (85 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 85.0/85.0 kB 4.6 MB/s eta 0:00:00
Downloading databricks_sdk-0.46.0-py3-none-any.whl (677 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 677.5/677.5 kB 24.1 MB/s eta 0:00:00
Downloading fastapi-0.115.11-py3-none-any.whl (94 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 94.9/94.9 kB 5.6 MB/s eta 0:00:00
Downloading graphql_relay-3.2.0-py3-none-any.whl (16 kB)
Downloading uvicorn-0.34.0-py3-none-any.whl (62 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.3/62.3 kB 3.2 MB/s eta 0:00:00
Downloading starlette-0.46.1-py3-none-any.whl (71 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 72.0/72.0 kB 4.2 MB/s eta 0:00:00
Installing collected packages: uvicorn, gunicorn, graphql-relay, starlette, graphene, fastapi, databricks-sdk, mlflow-skinny, mlflow
Successfully installed databricks-sdk-0.46.0 fastapi-0.115.11 graphene-3.4.3 graphql-relay-3.2.0 gunicorn-23.0.0 mlflow-2.21.0 mlflow-skinny-2.21.0 starlette-0.46.1 uvicorn-0.34.0

# შემდეგ cell - ში mlflow ზე ვინახავთ მხოლოდ საუკეთესო მოდელს

In [50]:
import mlflow
import mlflow.sklearn
import pandas as pd
import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import GridSearchCV, KFold
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler, MinMaxScaler

# Set up the MLflow experiment
mlflow.set_experiment("Logistic_Regression_Seminar")

# Your existing pipeline code
pipeline = Pipeline([
    ('scaler', StandardScaler()),
    ('classifier', LogisticRegression(max_iter=1000))
])
scalers = [
    StandardScaler(),
    MinMaxScaler(),
    None
]

kfold = KFold(n_splits=5, shuffle=True, random_state=42)
param_grid = {
    'scaler': scalers,
    'classifier__C': [0.1, 1, 10],
}

grid_search = GridSearchCV(
    pipeline,
    param_grid=param_grid,
    cv=kfold,
    scoring='f1',
    verbose=2,
    return_train_score=True
)

# Log each trial in the grid search
with mlflow.start_run(run_name="grid_search_test") as mlflow_run:
    run_id = mlflow_run.info.run_id
    print(run_id)
    
    # Log the parent experiment parameters
    mlflow.log_params({
        "cv_folds": kfold.n_splits,
        "scoring_metric": "f1",
        "random_state": 42,
        "model_type": "LogisticRegression"
    })
    
    # Fit the grid search
    grid_search.fit(X_train, y_train)
    
    # Log best model and parameters as parent run artifacts
    mlflow.log_param("best_params", grid_search.best_params_)
    mlflow.log_metric("best_cv_score", grid_search.best_score_)
    
    # Save best model
    mlflow.sklearn.log_model(grid_search.best_estimator_, "best_model")
    
    # Create a pandas DataFrame of results
    results = pd.DataFrame(grid_search.cv_results_)

# Print out the results
print(f"Best parameters: {grid_search.best_params_}")
print(f"Best cross-validation score: {grid_search.best_score_:.4f}")

2026/03/30 17:49:36 INFO mlflow.tracking.fluent: Experiment with name 'Logistic_Regression_Seminar' does not exist. Creating a new experiment.

06ac9d79c1194ef2a2f5d4d0fd6a33d8
Fitting 5 folds for each of 9 candidates, totalling 45 fits
[CV] END .........classifier__C=0.1, scaler=StandardScaler(); total time=   0.0s
[CV] END .........classifier__C=0.1, scaler=StandardScaler(); total time=   0.0s
[CV] END .........classifier__C=0.1, scaler=StandardScaler(); total time=   0.0s
[CV] END .........classifier__C=0.1, scaler=StandardScaler(); total time=   0.0s
[CV] END .........classifier__C=0.1, scaler=StandardScaler(); total time=   0.0s
[CV] END ...........classifier__C=0.1, scaler=MinMaxScaler(); total time=   0.0s
[CV] END ...........classifier__C=0.1, scaler=MinMaxScaler(); total time=   0.0s
[CV] END ...........classifier__C=0.1, scaler=MinMaxScaler(); total time=   0.0s
[CV] END ...........classifier__C=0.1, scaler=MinMaxScaler(); total time=   0.0s
[CV] END ...........classifier__C=0.1, scaler=MinMaxScaler(); total time=   0.0s
[CV] END .....................classifier__C=0.1, scaler=None; total time=   0.5s
[CV] END .....................classifier__C=0.1, scaler=None; total time=   0.4s
[CV] END .....................classifier__C=0.1, scaler=None; total time=   0.5s
[CV] END .....................classifier__C=0.1, scaler=None; total time=   0.3s
[CV] END .....................classifier__C=0.1, scaler=None; total time=   0.3s
[CV] END ...........classifier__C=1, scaler=StandardScaler(); total time=   0.0s
[CV] END ...........classifier__C=1, scaler=StandardScaler(); total time=   0.0s
[CV] END ...........classifier__C=1, scaler=StandardScaler(); total time=   0.0s
[CV] END ...........classifier__C=1, scaler=StandardScaler(); total time=   0.0s
[CV] END ...........classifier__C=1, scaler=StandardScaler(); total time=   0.0s
[CV] END .............classifier__C=1, scaler=MinMaxScaler(); total time=   0.0s
[CV] END .............classifier__C=1, scaler=MinMaxScaler(); total time=   0.0s
[CV] END .............classifier__C=1, scaler=MinMaxScaler(); total time=   0.0s
[CV] END .............classifier__C=1, scaler=MinMaxScaler(); total time=   0.0s
[CV] END .............classifier__C=1, scaler=MinMaxScaler(); total time=   0.0s
[CV] END .......................classifier__C=1, scaler=None; total time=   0.3s
[CV] END .......................classifier__C=1, scaler=None; total time=   0.5s
[CV] END .......................classifier__C=1, scaler=None; total time=   0.4s
[CV] END .......................classifier__C=1, scaler=None; total time=   0.4s
[CV] END .......................classifier__C=1, scaler=None; total time=   0.3s
[CV] END ..........classifier__C=10, scaler=StandardScaler(); total time=   0.0s
[CV] END ..........classifier__C=10, scaler=StandardScaler(); total time=   0.0s
[CV] END ..........classifier__C=10, scaler=StandardScaler(); total time=   0.0s
[CV] END ..........classifier__C=10, scaler=StandardScaler(); total time=   0.0s
[CV] END ..........classifier__C=10, scaler=StandardScaler(); total time=   0.0s
[CV] END ............classifier__C=10, scaler=MinMaxScaler(); total time=   0.0s
[CV] END ............classifier__C=10, scaler=MinMaxScaler(); total time=   0.0s
[CV] END ............classifier__C=10, scaler=MinMaxScaler(); total time=   0.0s
[CV] END ............classifier__C=10, scaler=MinMaxScaler(); total time=   0.0s
[CV] END ............classifier__C=10, scaler=MinMaxScaler(); total time=   0.0s
[CV] END ......................classifier__C=10, scaler=None; total time=   0.4s
[CV] END ......................classifier__C=10, scaler=None; total time=   0.3s
[CV] END ......................classifier__C=10, scaler=None; total time=   0.5s
[CV] END ......................classifier__C=10, scaler=None; total time=   0.3s
[CV] END ......................classifier__C=10, scaler=None; total time=   0.8s

2026/03/30 17:49:47 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/03/30 17:49:49 WARNING mlflow.sklearn: Saving scikit-learn models in the pickle or cloudpickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is the 'skops' format. For more information, see: https://scikit-learn.org/stable/model_persistence.html

🏃 View run grid_search_test at: https://dagshub.com/lukaLomadze/ML.mlflow/#/experiments/0/runs/06ac9d79c1194ef2a2f5d4d0fd6a33d8
🧪 View experiment at: https://dagshub.com/lukaLomadze/ML.mlflow/#/experiments/0
Best parameters: {'classifier__C': 0.1, 'scaler': StandardScaler()}
Best cross-validation score: 0.7161